method: random
metric:
  goal: minimize
  name: val/pearson
name: tune_counts_mse
parameters:
  mse_alpha:
    values: [0.75, 0.5]
  count_lr:
    values: [0.001, 0.0001]
  count_wd:
    values: [0.01, 0.001, 0.0001]
  count_dropout:
    values: [0.0, 0.05, 0.2]
  train_mode:
    value: count
  loss_mode:
    value: mse
  ckpt_file:
    value: '20240521_0110_petra_mode_masking_lr_0.001_wd_0.0001_batch_45_mlmp_0.7_seed1_hvg_pairing_GFpert.ckpt'
  src_dataset_folder:
    value: '../../datasets/Norman2019/dataset/filtered_tokenised_hvg_pairing_GFpert_control.dataset'
  tgt_dataset_folder:
    value: '../../datasets/Norman2019/dataset/filtered_tokenised_hvg_pairing_perturbed.dataset'
  src_adata_folder:
    value: '../../datasets/Norman2019/adata/filtered_tokenised_hvg_pairing_control.h5ad'
  tgt_adata_folder:
    value: '../../datasets/Norman2019/adata/filtered_tokenised_hvg_pairing_perturbed.h5ad'
  base_path:
    value: '/lustre/scratch126/cellgen/team361/ip14'
  batch_size:
    value: 70
  split:
    value: True
  splitting_mode:
    value: gears-simulation
  epochs:
    value: 15
  max_len:
    value: 1750
  n_workers:
    value: 16
  seed:
    value: 1
  tune_masking:
    value: False
  
program: /lustre/scratch126/cellgen/team361/ip14/Projects/2024Mar_Tperturb/T_perturb/T_perturb/train.py
project: ttransformer
